
# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-7.18

# Local packages, usually specified by relative directory name
packages:
- '.'
# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - snap-loader-dynamic-1.0.0.0
  - snap-loader-static-1.0.0.0
  - digestive-functors-0.8.2.0
  - digestive-functors-heist-0.8.7.0
  - digestive-functors-snap-0.7.0.0
  - snap-1.0.0.1
  - HDBC-sqlite3-2.3.3.1
  - heist-1.0.1.0
  - map-syntax-0.2.0.2

# Extra package databases containing global packages
extra-package-dbs: []
